### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ViperWolf263** [Mustachedom/md-drugs#15]
anyway this is useable without ui and buffs by PS i cant seem to get ps scripts working correctly for those but would really like to use this

**Comment by Mustachedom** [comment]
> anyway this is useable without ui and buffs by PS i cant seem to get ps scripts working correctly for those but would really like to use this 

Hello! Yes everything is open source and editable. For the ps mini game search through the client file for circle and delete the 
Export 
If success then
Else
End, number, number) lines 

As for buffs they are easier to remove by deleting the exports in the client pharma.lua

**Comment by ViperWolf263** [comment]
how would i use the mlo without the telepots ? would i just comment out that part of the client/meth.lua for example ?

**Comment by Mustachedom** [comment]
Meth and coke are hard locked to the IPL due to the animation sets they use because it requires coords and offsets and they are a pain in the ass to switch around

Everything else can be easily switched in the config

**Comment by ViperWolf263** [comment]
dang was hoping i could switch them out as i use a script for ipl labs already they can be entered using a key was hoping i can set this up using mlo labs

**Comment by Mustachedom** [comment]
you can make it locked behind a key, you just need to go to the target option where it teleports you

add item = ' ' above the action = function() line and it locks it behind the item

**Comment by ViperWolf263** [comment]
would that still use the ipl labs cause those already have drugs set up my teleport labs are used for gangs with another script was hoping i could use say this https://www.gta5-mods.com/maps/mlo-enhanced-coke-lab-sp-fivem-dvd6789 for the coke lab rather then a teleport

**Comment by Mustachedom** [comment]
you could move it to there, but it will be a little trickier especially with cocaine

the biggest issue you will find is the animation sets i use for the cutting and packaging cocaine arent as easy as changing the vector since they use offsets. so if you want to use the fancier animations, you can absolutely move it, but it will require a lot of editing

if you want to use regular animations for coke and meth, you will need to edit just a little bit

there is a function inside their target options, you just remove that and function and put an emote call/ progressbar in place of it and bada bing bada boop it will work

**Comment by ViperWolf263** [comment]
im having some trouble figuring out how to put the progress bar in for the meth and coke is there anyway at all you could edit those few lines for meth and coke i can set the locations and stuff up just having some trouble with the emote call just need the progress bar added you be a life saver hate to be a pest

**Comment by Mustachedom** [comment]
non-issue
