### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Badboi2k24** [Mustachedom/md-drugs#24]
Hello, Just wondering will this work with open MLO's? or just with teleport?

**Comment by VibrantRP** [comment]
It'll work with whatever you want @Badboi2k24 

All you've got to do is move the coords

**Comment by badboi2k2024** [comment]
The problem i'm having is with the animations when processing or cutting drugs, any tips on how to get them to work with other MLO's?

**Comment by Mustachedom** [comment]
cocaine and meth are hard coded for IPLs due to the animations they use. since its an animation set that has to work with offsets its a pain in the ass to set up so i made it locked to those locations in animationsandfunctions.lua

everything else can be moved anywhere throughout the config. Weed is in an IPL but can be moved fairly easy using only the config and weed.lua client sided
